default:
  image: docker:23

services:
  - docker:stable-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - apk add --no-cache curl jq py-pip
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region us-east-2)
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD https://index.docker.io/v1/

stages:
  - build

build:
  stage: build-backend
  before_script:
    - apk add --no-cache curl jq py-pip
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region us-east-2)
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD https://index.docker.io/v1/
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - echo "Build"
    - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG .
    - docker tag $CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG $REPOSITORY_URL/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
    - docker push $REPOSITORY_URL/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG