image: docker:stable
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

services:
- docker:stable-dind

build:
  stage: build
  before_script:
    - apk add --no-cache curl jq py-pip 
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region us-east-2)
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - echo "Build"
    - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG .
    - docker tag $CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG $REPOSITORY_URL/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
    - docker push $REPOSITORY_URL/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
  only:
    - develop
    - release
    - tags
