/*
Pelucio backend API

Pelucio backend http endpoints

API version: 1.0
Contact: contato@fourengine.com.br
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pelucioclient

import (
	"encoding/json"
)

// checks if the WalletWalletResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletWalletResponse{}

// WalletWalletResponse struct for WalletWalletResponse
type WalletWalletResponse struct {
	Balance *map[string]string `json:"balance,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	ExternalId *string `json:"external_id,omitempty"`
	Id *string `json:"id,omitempty"`
	LockedBalance *map[string]string `json:"lockedBalance,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewWalletWalletResponse instantiates a new WalletWalletResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletWalletResponse() *WalletWalletResponse {
	this := WalletWalletResponse{}
	return &this
}

// NewWalletWalletResponseWithDefaults instantiates a new WalletWalletResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletWalletResponseWithDefaults() *WalletWalletResponse {
	this := WalletWalletResponse{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *WalletWalletResponse) GetBalance() map[string]string {
	if o == nil || IsNil(o.Balance) {
		var ret map[string]string
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWalletResponse) GetBalanceOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *WalletWalletResponse) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given map[string]string and assigns it to the Balance field.
func (o *WalletWalletResponse) SetBalance(v map[string]string) {
	o.Balance = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WalletWalletResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWalletResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WalletWalletResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *WalletWalletResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *WalletWalletResponse) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWalletResponse) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *WalletWalletResponse) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *WalletWalletResponse) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WalletWalletResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWalletResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WalletWalletResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WalletWalletResponse) SetId(v string) {
	o.Id = &v
}

// GetLockedBalance returns the LockedBalance field value if set, zero value otherwise.
func (o *WalletWalletResponse) GetLockedBalance() map[string]string {
	if o == nil || IsNil(o.LockedBalance) {
		var ret map[string]string
		return ret
	}
	return *o.LockedBalance
}

// GetLockedBalanceOk returns a tuple with the LockedBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWalletResponse) GetLockedBalanceOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.LockedBalance) {
		return nil, false
	}
	return o.LockedBalance, true
}

// HasLockedBalance returns a boolean if a field has been set.
func (o *WalletWalletResponse) HasLockedBalance() bool {
	if o != nil && !IsNil(o.LockedBalance) {
		return true
	}

	return false
}

// SetLockedBalance gets a reference to the given map[string]string and assigns it to the LockedBalance field.
func (o *WalletWalletResponse) SetLockedBalance(v map[string]string) {
	o.LockedBalance = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *WalletWalletResponse) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWalletResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *WalletWalletResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *WalletWalletResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *WalletWalletResponse) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWalletResponse) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *WalletWalletResponse) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *WalletWalletResponse) SetVersion(v string) {
	o.Version = &v
}

func (o WalletWalletResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletWalletResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LockedBalance) {
		toSerialize["lockedBalance"] = o.LockedBalance
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableWalletWalletResponse struct {
	value *WalletWalletResponse
	isSet bool
}

func (v NullableWalletWalletResponse) Get() *WalletWalletResponse {
	return v.value
}

func (v *NullableWalletWalletResponse) Set(val *WalletWalletResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletWalletResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletWalletResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletWalletResponse(val *WalletWalletResponse) *NullableWalletWalletResponse {
	return &NullableWalletWalletResponse{value: val, isSet: true}
}

func (v NullableWalletWalletResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletWalletResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


