/*
Pelucio backend API

Pelucio backend http endpoints

API version: 1.0
Contact: contato@fourengine.com.br
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pelucioclient

import (
	"encoding/json"
)

// checks if the WalletWallet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletWallet{}

// WalletWallet struct for WalletWallet
type WalletWallet struct {
	Balance *map[string]map[string]interface{} `json:"balance,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	Id *string `json:"id,omitempty"`
	LockedBalance *map[string]map[string]interface{} `json:"lockedBalance,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewWalletWallet instantiates a new WalletWallet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletWallet() *WalletWallet {
	this := WalletWallet{}
	return &this
}

// NewWalletWalletWithDefaults instantiates a new WalletWallet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletWalletWithDefaults() *WalletWallet {
	this := WalletWallet{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *WalletWallet) GetBalance() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Balance) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWallet) GetBalanceOk() (*map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *WalletWallet) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given map[string]map[string]interface{} and assigns it to the Balance field.
func (o *WalletWallet) SetBalance(v map[string]map[string]interface{}) {
	o.Balance = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WalletWallet) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWallet) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WalletWallet) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *WalletWallet) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WalletWallet) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWallet) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WalletWallet) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WalletWallet) SetId(v string) {
	o.Id = &v
}

// GetLockedBalance returns the LockedBalance field value if set, zero value otherwise.
func (o *WalletWallet) GetLockedBalance() map[string]map[string]interface{} {
	if o == nil || IsNil(o.LockedBalance) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return *o.LockedBalance
}

// GetLockedBalanceOk returns a tuple with the LockedBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWallet) GetLockedBalanceOk() (*map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.LockedBalance) {
		return nil, false
	}
	return o.LockedBalance, true
}

// HasLockedBalance returns a boolean if a field has been set.
func (o *WalletWallet) HasLockedBalance() bool {
	if o != nil && !IsNil(o.LockedBalance) {
		return true
	}

	return false
}

// SetLockedBalance gets a reference to the given map[string]map[string]interface{} and assigns it to the LockedBalance field.
func (o *WalletWallet) SetLockedBalance(v map[string]map[string]interface{}) {
	o.LockedBalance = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *WalletWallet) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWallet) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *WalletWallet) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *WalletWallet) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *WalletWallet) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletWallet) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *WalletWallet) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *WalletWallet) SetVersion(v string) {
	o.Version = &v
}

func (o WalletWallet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletWallet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LockedBalance) {
		toSerialize["lockedBalance"] = o.LockedBalance
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableWalletWallet struct {
	value *WalletWallet
	isSet bool
}

func (v NullableWalletWallet) Get() *WalletWallet {
	return v.value
}

func (v *NullableWalletWallet) Set(val *WalletWallet) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletWallet) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletWallet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletWallet(val *WalletWallet) *NullableWalletWallet {
	return &NullableWalletWallet{value: val, isSet: true}
}

func (v NullableWalletWallet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletWallet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


