/*
Pelucio backend API

Pelucio backend http endpoints

API version: 1.0
Contact: contato@fourengine.com.br
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pelucioclient

import (
	"encoding/json"
)

// checks if the WalletCreateWalletModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletCreateWalletModel{}

// WalletCreateWalletModel struct for WalletCreateWalletModel
type WalletCreateWalletModel struct {
	Balance *map[string]int32 `json:"balance,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	Id *string `json:"id,omitempty"`
	LockedBalance *map[string]int32 `json:"lockedBalance,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewWalletCreateWalletModel instantiates a new WalletCreateWalletModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletCreateWalletModel() *WalletCreateWalletModel {
	this := WalletCreateWalletModel{}
	return &this
}

// NewWalletCreateWalletModelWithDefaults instantiates a new WalletCreateWalletModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletCreateWalletModelWithDefaults() *WalletCreateWalletModel {
	this := WalletCreateWalletModel{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *WalletCreateWalletModel) GetBalance() map[string]int32 {
	if o == nil || IsNil(o.Balance) {
		var ret map[string]int32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletCreateWalletModel) GetBalanceOk() (*map[string]int32, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *WalletCreateWalletModel) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given map[string]int32 and assigns it to the Balance field.
func (o *WalletCreateWalletModel) SetBalance(v map[string]int32) {
	o.Balance = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WalletCreateWalletModel) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletCreateWalletModel) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WalletCreateWalletModel) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *WalletCreateWalletModel) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WalletCreateWalletModel) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletCreateWalletModel) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WalletCreateWalletModel) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WalletCreateWalletModel) SetId(v string) {
	o.Id = &v
}

// GetLockedBalance returns the LockedBalance field value if set, zero value otherwise.
func (o *WalletCreateWalletModel) GetLockedBalance() map[string]int32 {
	if o == nil || IsNil(o.LockedBalance) {
		var ret map[string]int32
		return ret
	}
	return *o.LockedBalance
}

// GetLockedBalanceOk returns a tuple with the LockedBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletCreateWalletModel) GetLockedBalanceOk() (*map[string]int32, bool) {
	if o == nil || IsNil(o.LockedBalance) {
		return nil, false
	}
	return o.LockedBalance, true
}

// HasLockedBalance returns a boolean if a field has been set.
func (o *WalletCreateWalletModel) HasLockedBalance() bool {
	if o != nil && !IsNil(o.LockedBalance) {
		return true
	}

	return false
}

// SetLockedBalance gets a reference to the given map[string]int32 and assigns it to the LockedBalance field.
func (o *WalletCreateWalletModel) SetLockedBalance(v map[string]int32) {
	o.LockedBalance = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *WalletCreateWalletModel) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletCreateWalletModel) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *WalletCreateWalletModel) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *WalletCreateWalletModel) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *WalletCreateWalletModel) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletCreateWalletModel) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *WalletCreateWalletModel) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *WalletCreateWalletModel) SetVersion(v string) {
	o.Version = &v
}

func (o WalletCreateWalletModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletCreateWalletModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LockedBalance) {
		toSerialize["lockedBalance"] = o.LockedBalance
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableWalletCreateWalletModel struct {
	value *WalletCreateWalletModel
	isSet bool
}

func (v NullableWalletCreateWalletModel) Get() *WalletCreateWalletModel {
	return v.value
}

func (v *NullableWalletCreateWalletModel) Set(val *WalletCreateWalletModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletCreateWalletModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletCreateWalletModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletCreateWalletModel(val *WalletCreateWalletModel) *NullableWalletCreateWalletModel {
	return &NullableWalletCreateWalletModel{value: val, isSet: true}
}

func (v NullableWalletCreateWalletModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletCreateWalletModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


