/*
Pelucio backend API

Pelucio backend http endpoints

API version: 1.0
Contact: contato@fourengine.com.br
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pelucioclient

import (
	"encoding/json"
)

// checks if the WalletAmountModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletAmountModel{}

// WalletAmountModel struct for WalletAmountModel
type WalletAmountModel struct {
	Amount *string `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
}

// NewWalletAmountModel instantiates a new WalletAmountModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletAmountModel() *WalletAmountModel {
	this := WalletAmountModel{}
	return &this
}

// NewWalletAmountModelWithDefaults instantiates a new WalletAmountModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletAmountModelWithDefaults() *WalletAmountModel {
	this := WalletAmountModel{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *WalletAmountModel) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletAmountModel) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *WalletAmountModel) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *WalletAmountModel) SetAmount(v string) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *WalletAmountModel) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletAmountModel) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *WalletAmountModel) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *WalletAmountModel) SetCurrency(v string) {
	o.Currency = &v
}

func (o WalletAmountModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletAmountModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullableWalletAmountModel struct {
	value *WalletAmountModel
	isSet bool
}

func (v NullableWalletAmountModel) Get() *WalletAmountModel {
	return v.value
}

func (v *NullableWalletAmountModel) Set(val *WalletAmountModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletAmountModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletAmountModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletAmountModel(val *WalletAmountModel) *NullableWalletAmountModel {
	return &NullableWalletAmountModel{value: val, isSet: true}
}

func (v NullableWalletAmountModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletAmountModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


